// WARNING: DO NOT MANUALLY EDIT. This file is auto-generated by 'gen_ast_h.py'

#ifndef PLOX_AUTO_GENERATED_AST
#define PLOX_AUTO_GENERATED_AST

#include <memory>

#include <string>

#include <variant>

#include <scanner.h>

namespace plox {
namespace treewalk {
namespace ast {

struct Binary;

struct Grouping;

struct Literal;

struct Unary;

struct Variable;

using Expr = std::variant<Binary, Grouping, Literal, Unary, Variable>;

struct Binary {
  std::unique_ptr<Expr> left;
  Token op;
  std::unique_ptr<Expr> right;
};

struct Grouping {
  std::unique_ptr<Expr> expr;
};

struct Literal {
  std::string_view value;
  TokenType type;
};

struct Unary {
  Token op;
  std::unique_ptr<Expr> right;
};

struct Variable {
  std::string_view name;
};

} // namespace ast
} // namespace treewalk
} // namespace plox

#endif // PLOX_AUTO_GENERATED_AST
