// WARNING: DO NOT MANUALLY EDIT. This file is auto-generated by 'gen_ast_h.py'

#ifndef PLOX_AUTO_GENERATED_AST
#define PLOX_AUTO_GENERATED_AST

#include <memory>

#include <string>

#include <variant>

#include <scanner.h>

namespace plox {
namespace treewalk {
namespace ast {

struct Assign;

struct Binary;

struct Call;

struct Get;

struct Grouping;

struct Literal;

struct Set;

struct Unary;

struct Variable;

using Expr = std::variant<Assign, Binary, Call, Get, Grouping, Literal, Set,
                          Unary, Variable>;

struct Assign {
  std::string_view name;
  std::unique_ptr<Expr> value;
};

struct Binary {
  std::unique_ptr<Expr> left;
  Token op;
  std::unique_ptr<Expr> right;
};

struct Call {
  std::unique_ptr<Expr> callee;
  std::vector<std::unique_ptr<Expr>> args;
};

struct Get {
  std::unique_ptr<Expr> object;
  std::string_view property;
};

struct Grouping {
  std::unique_ptr<Expr> expr;
};

struct Literal {
  std::string_view value;
  TokenType type;
};

struct Set {
  std::unique_ptr<Expr> object;
  std::string_view property;
  std::unique_ptr<Expr> value;
};

struct Unary {
  Token op;
  std::unique_ptr<Expr> right;
};

struct Variable {
  std::string_view name;
};

} // namespace ast
} // namespace treewalk
} // namespace plox

#endif // PLOX_AUTO_GENERATED_AST
