// WARNING: DO NOT MANUALLY EDIT. This file is auto-generated by 'gen_ast_h.py'

#ifndef PLOX_AUTO_GENERATED_STMT
#define PLOX_AUTO_GENERATED_STMT

#include <ast.h>

#include <memory>

#include <variant>

namespace plox {
namespace treewalk {
namespace stmt {

struct Block;

struct If;

struct Expression;

struct Print;

struct VarDecl;

using Stmt = std::variant<Block, If, Expression, Print, VarDecl>;

struct Block {
  std::vector<std::unique_ptr<stmt::Stmt>> stmts;
};

struct If {
  std::unique_ptr<ast::Expr> condition;
  std::unique_ptr<stmt::Stmt> ifBranch;
  std::unique_ptr<stmt::Stmt> elseBranch;
};

struct Expression {
  std::unique_ptr<ast::Expr> expr;
};

struct Print {
  std::unique_ptr<ast::Expr> expr;
};

struct VarDecl {
  std::string_view name;
  std::unique_ptr<ast::Expr> expr;
};

} // namespace stmt
} // namespace treewalk
} // namespace plox

#endif // PLOX_AUTO_GENERATED_STMT
